name: 'mrt_project_dbt'
version: '1.0.0'
config-version: 2

profile: 'mrt_project_dbt'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  mrt_project_dbt:

    # Bronze Layer
    bronze:
      +schema: bronze
      +materialized: table

    # Silver Layer
    silver:
      +schema: gold_silver
      +materialized: table

    # Gold Layer
    gold:
      +schema: gold_gold       # ✅ force this schema
      +materialized: table

      gold_station_crowd_map:
        +materialized: table

